export const USER_LOAADING="USER_LOAADING";
export const USER_LOAADED="USER_LOAADED";
export const AUTH_ERROR="AUTH_ERROR";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";
export const GET_ERRORS="GET_ERRORS";
export const CLEAR_ERRORS="CLEAR_ERRORS";

